### ISSUE TITLE
Publish new NPM package including MetaMask and ERCs

### ISSUE THREAD

**Issue by imagobea** [maticnetwork/nightfall-sdk#125]
### TODO

- [ ] Enable `ercList` filters (#98 and #99)
- [x] Ensure good coverage (see #17)
- [x] Clean up example scripts (see #118)
- [x] Polish example web-app (see #115 and upcoming issues - it is important that we enable inputs for parameters)
- [x] Review README - provides minimum info re web-app (make sure we are happy in the overall with the sdk docs)

Would be good to have #76 and #90.

Bear #96 in mind when publishing - if this is still manual step, create a tag.
