### ISSUE TITLE
Individual user can export their commitments from db

### ISSUE THREAD

**Issue by druiz0992** [maticnetwork/nightfall-sdk#15]
### Investigate
- [x] Decide what data do we export (just commitments, perhaps transactions too)
  - Just commitments are necessary.
- [x] Figure out if the endpoints that get onChain and the other which get offChain commitments are enough to get all the commitments by user. Or if will be necessary to create a more specific endpoint in the client.
- [x] **If was necessary to create a new endpoint**, how to select/export only the commitments they own - what keys do we need, and how do we pass them securely?
  - **We'll have a new query to get all the commitments and a logic function to filter commitments by compressed pkd and return just the user's commitments**.
- [x] Understand the exact return format from the endpoints.

### Tasks
- [x] Drawn the flow for this useCase.
- [x] Create the unit tests for each functions existent in the flow.
- [x] Create the functions after tests cases be created.
- [x] Create one E2E test with a mocked api.
- [x] Create the function that call all the others functions necessary to the complete flow.
- [x] Create an example script.
- [x] If was necessary to create a new endpoint, create the tests for this new client endpoint.
- [x] Add an endpoint to `nightfall-client` API to get all commitments
- [x] Create a logic function to filter commitments by compressed pkd and return just the user's commitments
- [ ] After understand the return object format from endpoints, update the commitments mock file to be used in the tests.
- [x] Change the getCommitments function in client class with the new endpoint route.

### Flow
![image.png](https://images.zenhubusercontent.com/61e15c65574e2d57bb040461/01261b76-865c-43dd-8afc-0cf379d16b91)

### Notes
- [Wallet import/export flow PR715](https://github.com/EYBlockchain/nightfall_3/pull/715)
- Client can rebuild transactions + block + timber by going through past `BlockProposed` events from `State.sol`

**Comment by imagobea** [comment]
Original  description:

Define User SDK with the following functionalities

- connect to environment: covered by #14
- transactions: see #14, #21, #22
- check balance: see #14, #21, #22
- check proposers
- import/export commitments

**Comment by imagobea** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/PNF-6295dbd03832a40014480c20/issues/maticnetwork/nightfall-sdk/15?planning-poker) with ZenHub @imagobea @daveroga @luizoamorim @israelboudoux

**Comment by luizoamorim** [comment]
## What we have until here?

The flow drawn is covered with functions, unit tests and one integration test with api mocked.

### Endpoints
In one of our sdk daily, @daveroga showed us how the client is working, how spin it and how to set the SDK to make the communication with client.

I've created a script in examples folder and the communication is working well when we have the client up. 

Until now I understood that the route commitments/commitment, to be more specif the function getWalletCommitments in client/service/commitment-storage.mjs is returning the commitments onChain for the user that is calling.
I know that we have other endpoint that return the offChain commitments also that we need to use.

The getWalletCommitments is returning an object: { commitments: {} }

![image.png](https://images.zenhubusercontent.com/61e15c65574e2d57bb040461/eebee3d1-8976-4fd3-b1a6-d167614a9851)

## What we need from now?
- Figure out if the endpoints that get onChain and the other which get offChain commitments are enough to get all the commitments by user. Or if will be necessary to create a more specific endpoint.
- I'm using fs library from Javascript to create the file. I'm not encrypting the file. We need to decide if some kind of security layer will be necessary.
- We should define exactly the correct format for the file. Until now I'm exported in json format.

## Update
I'll update the issue description with this needs.
