### ISSUE TITLE
User can make transfers

### ISSUE THREAD

**Issue by imagobea** [maticnetwork/nightfall-sdk#22]
Enable offchain/onchain transfers. Please note that the actual offchain/onchain logic lives in the API: nightfall-client/src/services/transfer.mjs.

Transfer endpoint uses flag `offchain`.

From the SDK:
- Transfer offchain `true` -> all we need is calling endpoint `/transfer`
- Transfer offchain `false` (ie onchain) -> wait for `/transfer` response -> web3 sign `response.txDataToSign` -> web3 submit signed tx

### Tasks

- [x] Add new async method `transfer` to `Client` class, FYI method parameters are the same as existing deposit PLUS `offchain<boolean>`

- [x] Create a new file `transfer.ts` under lib/transactions, define async function `createAndSubmitTransfer`

- [x] Like the existing deposit transaction, `createAndSubmitTransfer` 1) calls `client.transfer`, 2) processes response - please refer to original nf3.transfer about how to process the client response, 3) if `!offchain` calls `submitTransaction`

- [x] Add async method `makeTransfer` to `User` class, try to stick to same steps in `makeDeposit`, i.e. format -> set token -> convert values -> `createAndSubmitTransfer` (approval NOT needed)

- [x] User method `makeTransfer` will take an `options` object. Please validate this object.

- [x] Add a `transfer` script to examples - follow deposit. How can we provide more info re offchain/onchain transfers - do we need more scripts?

- [x] Document as much as possible following JSDocs

- [x] Tests TBD
