### ISSUE TITLE
User can check current proposer

### ISSUE THREAD

**Issue by imagobea** [maticnetwork/nightfall-sdk#23]
For now we can focus on the `getCurrentProposer` method. We can implement `getProposers` later.

**Tasks in nightfall_3**
- [ ] Please create an issue in `nightfall_3` to create an endpoint + tests in the client API (nightfall_3/nightfall-client)
- [ ] Add the endpoint mentioned above
- [ ] Add test(s)

**Tasks in nightfall-sdk**
- [ ] Expand the sdk
- [ ] Add unit tests
- [ ] Document new methods
- [ ] Add example scripts
