### ISSUE TITLE
Individual user can import their commitments to db

### ISSUE THREAD

**Issue by imagobea** [maticnetwork/nightfall-sdk#29]
### Tasks
- [x] Add a client function
- [x] Add a user function
- [x] Verify if all the commitments imported from the file are of Commitment Type
- [x] Verify if  all compressedZkpPublicKey of the commitments imported from the file match with the user compressedZkpPublicKey
- [x] Logs
- [x] Function documentation
- [x] Tests
- [x] Example script

### Investigate
- [ ] Syncing (Issue #681 might be relevant)
