### ISSUE TITLE
Add missing Joi validations

### ISSUE THREAD

**Issue by imagobea** [maticnetwork/nightfall-sdk#76]
### Tasks

- [ ] Add/enable Joi validation for `exportCommitments` options
- [ ] Add/enable Joi validation for `importAndSaveCommitments` options
- [ ] Enhance `makeTransferOptions.nightfallRecipientAddress` - add a "custom validation"

Validations live in libs/user/validations.ts file. Enable validations in user/user.ts file.

For validating nightfall addresses with a custom validation function just follow the `isChecksum` implementation.

**Comment by imagobea** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/PNF-6295dbd03832a40014480c20/issues/maticnetwork/nightfall-sdk/76?planning-poker) with ZenHub @imagobea @luizoamorim

**Comment by imagobea** [comment]
@luizoamorim I'm moving the story to the backlog, let's focus on the release and come back to "new developments" later

**Comment by imagobea** [comment]
Updating issue to cover other missing validations re export/import.

**Comment by imagobea** [comment]
This issue is no longer valid
