### ISSUE TITLE
SDK integration in webApp

### ISSUE THREAD

**Issue by imagobea** [maticnetwork/nightfall-sdk#78]
Most of the uses of the SDK will be done through a web app. Web apps often integrate with browser wallets like MetaMask to manage Eth keys and signing transactions.

It looks like this could be easily achieved by making the `ethereumPrivateKey` optional, then adding some logic based on window object for setting a Web3 provider, but both assumptions require further investigation.

Another question is in terms of architecture. To make sure that integrating with a client is okay, as well as storing data outside the browser.

### Tasks

- [x] To better understand web3 provider - MetaMask
- [x] Main changes: web3 management, `submitTransaction`, making `ethPrivateKey` optional
- [ ] Unit tests for `submitTransaction`

**Comment by luizoamorim** [comment]
Was what I though about implement a react app using the current SDK. Use the window to manipulate the transactions. But for sure will spend some time about investigation.

In terms of architecture we can implement the Interface for repositories (data base manipulation) with the methods required. If the user want to use indexdb implement the Repository interface and instantiate a indexeddb object otherwise implement the interface and for each function call some client with the endpoint related that really will do the data manipulation.

What do you think?

**Comment by imagobea** [comment]
Hi @luizoamorim just coming back to this issue now.
So your comment is right, but for September we just need to have something that works.
Later, when we decide to use the SDK in the wallet, we can work towards detaching logic so that any db can be used, like you suggest.
